### ISSUE TITLE
AttributeError when trying to load replay

### ISSUE THREAD

**Issue by stefanpantic** [StoicLoofah/spawningtool#42]
I get this error when I try to load a replay using the CLI.

```Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/stefan/Documents/ML/env/src/spawningtool/spawningtool/__main__.py", line 124, in <module>
    main()
  File "/home/stefan/Documents/ML/env/src/spawningtool/spawningtool/__main__.py", line 113, in main
    include_map_details=bool(args.map_details))
  File "/home/stefan/Documents/ML/env/src/spawningtool/spawningtool/parser.py", line 830, in parse_replay
    return parser.get_parsed_data(cutoff_time, cache_dir, include_map_details)
  File "/home/stefan/Documents/ML/env/src/spawningtool/spawningtool/parser.py", line 198, in get_parsed_data
    self.load_replay()
  File "/home/stefan/Documents/ML/env/src/spawningtool/spawningtool/parser.py", line 274, in load_replay
    self.replay = sc2reader.load_replay(self.replay_file)
  File "/home/stefan/Documents/ML/env/lib/python3.6/site-packages/sc2reader/factories/sc2factory.py", line 85, in load_replay
    return self.load(Replay, source, options, **new_options)
  File "/home/stefan/Documents/ML/env/lib/python3.6/site-packages/sc2reader/factories/sc2factory.py", line 137, in load
    return self._load(cls, resource, filename=filename, options=options)
  File "/home/stefan/Documents/ML/env/lib/python3.6/site-packages/sc2reader/factories/sc2factory.py", line 146, in _load
    obj = cls(resource, filename=filename, factory=self, **options)
  File "/home/stefan/Documents/ML/env/lib/python3.6/site-packages/sc2reader/resources.py", line 312, in __init__
    engine.run(self)
  File "/home/stefan/Documents/ML/env/lib/python3.6/site-packages/sc2reader/engine/engine.py", line 177, in run
    for new_event in (event_handler(event, replay) or []):
  File "/home/stefan/Documents/ML/env/lib/python3.6/site-packages/sc2reader/engine/plugins/context.py", line 57, in handleTargetUnitCommandEvent
    self.last_target_ability_event[event.player.pid] = event
AttributeError: 'NoneType' object has no attribute 'pid'
```

**Comment by StoicLoofah** [comment]
Thanks for reporting this. We will track progress on this ticket in https://github.com/ggtracker/sc2reader/issues/61
