### ISSUE TITLE
No tracker data could be found, despite this being the right version (55958). Sorry.

### ISSUE THREAD

**Issue by windowshopr** [StoicLoofah/spawningtool#60]
Python 3, Windows 10, SC2 version 5.0.9, likely trying to process an old replay version, but I don't know.

```
C:\Program Files (x86)\StarCraft II\Replays>python -m spawningtool replay1.SC2Replay

Traceback (most recent call last):
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\spawningtool\__main__.py", line 113, in main
    include_map_details=bool(args.map_details))
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\spawningtool\parser.py", line 836, in parse_replay
    return parser.get_parsed_data(cutoff_time, cache_dir, include_map_details)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\spawningtool\parser.py", line 218, in get_parsed_data
    self.check_replay_version()
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\spawningtool\parser.py", line 286, in check_replay_version
    ), self.parsed_data)
spawningtool.exception.ReplayFormatError: No tracker data could be found, despite this being the right version (55958). Sorry.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\spawningtool\__main__.py", line 124, in <module>
    main()
  File "C:\Users\chalu\AppData\Roaming\Python\Python37\site-packages\spawningtool\__main__.py", line 117, in main
    print(error.message)
AttributeError: 'ReplayFormatError' object has no attribute 'message'
```

**Comment by StoicLoofah** [comment]
Can you share the replay that you're trying to parse? Where did you get the replay from?

**Comment by windowshopr** [comment]
It would have been one of the ones from the 2017 batch ladders I believe, but I have since found another parser that works on it. I will keep plugging away and if I find one that's specific here I'll post it. Thanks!!!
